/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp3ej2;

/**
 *
 * @author Valentin
 */
public class ConversorTemperatura extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConversorTemperatura.class.getName());

    /**
     * Creates new form ConversorTemperatura
     */
    public ConversorTemperatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jlTexto = new javax.swing.JLabel();
        jtGrados = new javax.swing.JTextField();
        jrFahrenheit = new javax.swing.JRadioButton();
        jrKelvin = new javax.swing.JRadioButton();
        jrCelsius = new javax.swing.JRadioButton();
        jrRadianes = new javax.swing.JRadioButton();
        jbConvertidor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(43, 174, 192));

        jlTitulo.setBackground(new java.awt.Color(51, 204, 255));
        jlTitulo.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jlTitulo.setText("CONVERSOR DE TEMPERATURA");

        jlTexto.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jlTexto.setText("Ingrese la temperatura en Grados:");

        jrFahrenheit.setText("A Fahrenheit");
        jrFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrFahrenheitActionPerformed(evt);
            }
        });

        jrKelvin.setText("A Kelvin");
        jrKelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrKelvinActionPerformed(evt);
            }
        });

        jrCelsius.setText("A Celsius");
        jrCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrCelsiusActionPerformed(evt);
            }
        });

        jrRadianes.setText("A Radianes");
        jrRadianes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrRadianesActionPerformed(evt);
            }
        });

        jbConvertidor.setBackground(new java.awt.Color(153, 153, 153));
        jbConvertidor.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jbConvertidor.setText("CONVERTIR");
        jbConvertidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConvertidorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrFahrenheit)
                                    .addComponent(jrKelvin))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrRadianes)
                                    .addComponent(jrCelsius))
                                .addGap(21, 21, 21))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jbConvertidor, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrCelsius)
                            .addComponent(jrFahrenheit))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrKelvin)
                            .addComponent(jrRadianes)))
                    .addComponent(jtGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jbConvertidor, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrFahrenheitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrFahrenheitActionPerformed

    private void jrKelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrKelvinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrKelvinActionPerformed

    private void jrCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrCelsiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrCelsiusActionPerformed

    private void jrRadianesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrRadianesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrRadianesActionPerformed

    private void jbConvertidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConvertidorActionPerformed
        // TODO add your handling code here:
        
        String txtIngresado = jtGrados.getText().trim();
        
        if (txtIngresado.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Por favor, ingrese una temperatura.", 
            "Atención", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        
        double celsius = Double.parseDouble(txtIngresado);
        double resultado = 0;
        String mensaje = "";
        
        if (jrFahrenheit.isSelected()){
            resultado = celsius * 9/5 + 32;
            mensaje = "La temperatura en grados Fahrenheit es: " + resultado;
        } else if (jrKelvin.isSelected()) {
            resultado = celsius + 273.5;
            mensaje = "La temperatura en grados Kelvin es: " + resultado;
        } //else if (jrRadianes.isSelected()){
            //resultado = celsius 
        else if (jrCelsius.isSelected()){
            resultado = celsius;
            mensaje = "La temperatura en grados celsius es: " + resultado;          
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "seleccione una unidad");
        return;
        }

        javax.swing.JOptionPane.showMessageDialog(this, 
        mensaje, 
        "Conversion", 
        javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        
        
  
    }//GEN-LAST:event_jbConvertidorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConversorTemperatura().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbConvertidor;
    private javax.swing.JLabel jlTexto;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JRadioButton jrCelsius;
    private javax.swing.JRadioButton jrFahrenheit;
    private javax.swing.JRadioButton jrKelvin;
    private javax.swing.JRadioButton jrRadianes;
    private javax.swing.JTextField jtGrados;
    // End of variables declaration//GEN-END:variables
}
